export const CATEGORIES = {
  NGAN_HANG:
    'ABB,ACB,BAB,BID,BVB,CTG,EIB,HDB,KLB,LPB,MBB,MSB,NAB,NVB,OCB,PGB,SGB,SHB,STB,TCB,TPB,VBB,VCB,VIB,VPB,SSB,VAB',
  CHUNG_KHOAN:
    'AAS,AGR,APG,BSI,BVS,CTS,EVF,EVS,FTS,HCM,MBS,SBS,SHS,SSI,VCI,VDS,VIX,VND,APS,HBS,IVS,ORS,TVB,TVS,VIG,WSS,BMS,TCI,VFS',
  THEP: 'BVG,HMC,HPG,HSG,NKG,POM,SHA,SHI,SMC,TLH,TVN,VGS,TNS,VCA,KVC,NSH,ITQ',
  DAU_KHI:
    'BSR,CNG,GAS,OIL,PET,PLX,POW,PSH,PVB,PVC,PVD,PVS,PVT,PVX,PXS,PGC,PLC',
  BAO_HIEM: 'BVH,BMI,MIG,PVI,BIC,ABI,VNR',
  BAT_DONG_SAN:
    'AGG,BII,CCL,CEO,DIG,DLG,DPG,DRH,DTD,DXG,HAR,HBC,HDC,HDG,HLD,HQC,HUT,IJC,KDH,LGL,MCG,NBB,NDN,NTL,NVL,PDR,SCR,TCH,TDH,VHM,VIC,VPH,VRE,HTN,VMC,CRE,DTA,HAG,IDJ,IDV,ITC,NHA,OGC,SGR,AAV,API,DXS,FIR,HPX,KHG,NRC,PWA,TEG,VPI,VRC',
  BDS_KCN:
    'D2D,GVR,IDC,ITA,KBC,LDG,LHG,NLG,NTC,PHR,QCG,REE,SIP,SJS,SZC,SZL,TDC,TIG,TIP',
  XD_VLXD:
    'VCG,VC7,HU4,MST,ROS,VC3,ACC,QNC,SCL,VGC,BCE,CSC,HTI,TTB,APC,C69,CDO,CRC,HID,HVH,LIG,PAS,S99,SCG,SCI,SDP,TLD,UDJ,EVG,CTD,PHC,CKG',
  DAU_TU_CONG:
    'BCC,BTS,C32,C47,C4G,CII,CTI,DHA,FCN,G36,HOM,HT1,KSB,LCG,SD5,SD6,SD9,TCD,THG,TV2',
  CAO_SU: 'DPR,DRC,DRI,GVR,PHR,VHG,HNG',
  DET_MAY: 'ADS,EVE,FTM,GIL,KMR,MSH,STK,TCM,TNG,VGT',
  THAN_KHOANG_SAN:
    'CLX,KSB,MDC,NBC,NNC,TDN,THT,TVD,VEF,CST,BMC,DHM,KHB,KSQ,MSR,TC6,TNT',
  THUY_SAN: 'ACL,ANV,ASM,CMX,FMC,IDI,MPC,VHC',
  THUC_PHAM_XK:
    'AFX,DBC,DHC,GTN,KDC,LTG,MHC,MSN,NAF,PTB,TNA,VCS,VLC,VNM,VOC,APF,BNA,KDF,MCM,MLS,TAR,VHE',
  HOA_CHAT_PHAN_BON: 'BFC,CSV,DCM,DDV,DGC,DPM,LAS,LIX,QBS,TSC,PMB,SBV,HCD,ABS',
  BLE_CONG_NGHE:
    'CMG,DGW,ELC,FOX,FPT,FRT,ITD,MWG,PET,PNJ,SAB,SGT,SAM,SRA,TTN,CTR,VGI',
  CANG_VAN_TAI:
    'DVP,DXP,GMD,HAH,PHP,PVP,PVT,SGP,SKG,SWC,TCL,TCW,VIP,VOS,VSC,VTO,STG,GSP,HHG,TCO,TMS,VNA,ILB,PVP',
  DICH_VU: 'HAX,PAN,TCT,VNG,VTP,KLF',
  DIEN_NANG_LUONG: 'KHP,PPC,PVG,QTP,VSH,TTA,GEG,SJD,NT2,REE,PC1,HND,GEX,VNE',
  DTPT: 'EID,FID,FIT,HHS,SJF,VCR,SHN',
  DUONG_GO: 'GDT,LSS,QNS,SBT,TTF',
  HANG_KHONG_DU_LICH: 'ACV,AST,HVN,SAS,VJC,VTD,NCT,DAH,RIC',
  NUOC_NHUA: 'AAA,APH,BMP,BWE,DAG,NTP,TDM,VNP,HII,NHH,PGN,PLP',
  SXKD: 'DQC,HAP,NAG,PAC,RAL,SAV,TLG',
  Y_TE_DUOC: 'AMV,DBD,DCL,DHG,DMC,DVN,JVC,TNH',
};
